// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDttTkQI4q6R_AkhLKtSOVV2bx2fMRn0Ro',
    appId: '1:306909454051:web:f1798811a65338400c2fd6',
    messagingSenderId: '306909454051',
    projectId: 'codeclub-b8e50',
    authDomain: 'codeclub-b8e50.firebaseapp.com',
    storageBucket: 'codeclub-b8e50.firebasestorage.app',
    measurementId: 'G-SFCPCDHZLJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBpA0WKmrRigpZz1BsNlE-pmzcPjJi_Veo',
    appId: '1:306909454051:android:fb4bdd5e8e9d83830c2fd6',
    messagingSenderId: '306909454051',
    projectId: 'codeclub-b8e50',
    storageBucket: 'codeclub-b8e50.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB0Z_zf8dN38afs3zexz9e0jAdKwa49CZo',
    appId: '1:306909454051:ios:3082724df81d488f0c2fd6',
    messagingSenderId: '306909454051',
    projectId: 'codeclub-b8e50',
    storageBucket: 'codeclub-b8e50.firebasestorage.app',
    iosBundleId: 'com.example.codeclub',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB0Z_zf8dN38afs3zexz9e0jAdKwa49CZo',
    appId: '1:306909454051:ios:3082724df81d488f0c2fd6',
    messagingSenderId: '306909454051',
    projectId: 'codeclub-b8e50',
    storageBucket: 'codeclub-b8e50.firebasestorage.app',
    iosBundleId: 'com.example.codeclub',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDttTkQI4q6R_AkhLKtSOVV2bx2fMRn0Ro',
    appId: '1:306909454051:web:4dde77a122c7f7bc0c2fd6',
    messagingSenderId: '306909454051',
    projectId: 'codeclub-b8e50',
    authDomain: 'codeclub-b8e50.firebaseapp.com',
    storageBucket: 'codeclub-b8e50.firebasestorage.app',
    measurementId: 'G-FJZTHELKZ7',
  );

}